name: webview_flutter_x_example
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter_x:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# Plus's overrides are ignored when this example is the pub root.
dependency_overrides:
  webview_flutter:
    path: ../webview_flutter
  webview_flutter_wkwebview:
    path: ../wkwebview_flutter
  webview_flutter_android:
    path: ../webview_flutter_android

flutter:

  uses-material-design: true

  assets:
    - assets/index.html
    - assets/style.css
    - assets/script.js
